### ISSUE TITLE
Mover o repositório para uma conta OldsGame com vários projetos de jogos dentro

### ISSUE THREAD

**Issue by ricardogpsf** [henriquegogo/oldsgame#2]
Pessoal, o que acham de movermos o repo pra uma conta do time?
Com isso podemos ter vários repositórios dentro sem que fique dependendo de um dono do repo, por exemplo, as configurações podem ser feitas por várias pessoas, etc.

@henriquegogo nada contra você ser o dono, mas..... 🤣 🤣

**Comment by henriquegogo** [comment]
kkkkkkkk, eu apoio

**Comment by paulobruno** [comment]
Apoiado, pode arrochar a criação

**Comment by ricardogpsf** [comment]
Feito! O novo repositório é https://github.com/oldsgame/tic-tac-toe.
